

title: MS | Mathematical Society
email: I don't know.
description: >- # this means to ignore newlines until 
More info coming soon
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mathematical-soceity.vercel.app/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  MS
author: Mathematical Society



